// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2jAh7Ye8lsK_w0OM3zd7174TzwKICFc',
    appId: '1:460585639171:android:5e2e82d6b74539f1d05d36',
    messagingSenderId: '460585639171',
    projectId: 'rubix25-bb41f',
    storageBucket: 'rubix25-bb41f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJnZ8MBnemVLOtJ8FczysFBa6Fb7EsSPg',
    appId: '1:460585639171:ios:945d042ddf6a1ac5d05d36',
    messagingSenderId: '460585639171',
    projectId: 'rubix25-bb41f',
    storageBucket: 'rubix25-bb41f.firebasestorage.app',
    androidClientId:
        '460585639171-1nurgjs8qroebq3fq3s1damolej0bche.apps.googleusercontent.com',
    iosClientId:
        '460585639171-k0vgmcsdg03aqlkdhjj64a9v1r18m8q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonAppRubix',
  );
}
